name: darkverse
description: "Bug WhatsApp Crasher"
publish_to: 'none'
version: 7.5.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  image_picker: ^1.0.7
  intl: ^0.19.0
  url_launcher: ^6.2.6
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  device_info_plus: ^10.1.0
  carousel_slider: 4.0.0
  web_socket_channel: ^2.4.0
  network_info_plus: ^4.1.0
  permission_handler: ^11.0.1
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.1
  share_plus: ^7.0.1
  shimmer: ^3.0.0
  webview_flutter: ^4.13.1
  geolocator: ^13.0.2
  geocoding: ^2.1.1
  audio_service: ^0.18.12
  just_audio: ^0.9.43
  video_player: ^2.9.3
  chewie: ^1.8.5
  socket_io_client: ^2.0.3+1
  local_auth: ^2.1.8
  
  # ============ TAMBAHAN UNTUK TOOLS ============
  file_picker: ^8.0.0
  wifi_iot: ^0.3.0
  fluttertoast: ^8.2.1
  # ============================================

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# HAPUS dependency_overrides juga
# dependency_overrides:
#   file_picker: 5.3.3
#   win32: 5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: assets/icon/icon.jpg
  image_path_ios: assets/icon/icon/icon.jpg
  image_path: assets/icon/icon.jpg
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg
    - assets/images/background.jpg
    - assets/images/logo.png
    - assets/videos/login.mp4
    - assets/videos/bg_profile.mp4
    - assets/videos/bug.mp4
    - assets/videos/background.mp4
    - assets/icon/icon.jpg
    - assets/sound/background.mp3

  fonts:
    - family: Orbitron
      fonts:
        - asset: fonts/Orbitron-Regular.ttf
    - family: ShareTechMono
      fonts:
        - asset: fonts/ShareTechMono-Regular.ttf