import 'package:shared_preferences/shared_preferences.dart';

class Lang {
  static String _current = 'id';
  static String get current => _current;

  static const Map<String, String> _meta = {
    'id': '🇮🇩 Indonesia', 'en': '🇬🇧 English', 'ar': '🇸🇦 العربية',
    'es': '🇪🇸 Español', 'pt': '🇧🇷 Português', 'fr': '🇫🇷 Français',
    'de': '🇩🇪 Deutsch', 'ja': '🇯🇵 日本語', 'ko': '🇰🇷 한국어',
    'zh': '🇨🇳 中文', 'ru': '🇷🇺 Русский', 'hi': '🇮🇳 हिन्दी',
    'tr': '🇹🇷 Türkçe', 'th': '🇹🇭 ไทย', 'vi': '🇻🇳 Tiếng Việt',
    'ms': '🇲🇾 Bahasa Melayu', 'tl': '🇵🇭 Filipino', 'it': '🇮🇹 Italiano',
    'nl': '🇳🇱 Nederlands', 'pl': '🇵🇱 Polski', 'sv': '🇸🇪 Svenska',
    'da': '🇩🇰 Dansk', 'no': '🇳🇴 Norsk', 'fi': '🇫🇮 Suomi',
    'cs': '🇨🇿 Čeština', 'sk': '🇸🇰 Slovenčina', 'ro': '🇷🇴 Română',
    'hu': '🇭🇺 Magyar', 'el': '🇬🇷 Ελληνικά', 'he': '🇮🇱 עברית',
    'uk': '🇺🇦 Українська', 'bn': '🇧🇩 বাংলা', 'ta': '🇮🇳 தமிழ்',
    'te': '🇮🇳 తెలుగు', 'ml': '🇮🇳 മലയാളം', 'kn': '🇮🇳 ಕನ್ನಡ',
    'mr': '🇮🇳 मराठी', 'gu': '🇮🇳 ગુજરાતી', 'pa': '🇮🇳 ਪੰਜਾਬੀ',
    'ur': '🇵🇰 اردو', 'fa': '🇮🇷 فارسی', 'sw': '🇰🇪 Kiswahili',
    'af': '🇿🇦 Afrikaans', 'sq': '🇦🇱 Shqip', 'am': '🇪🇹 አማርኛ',
    'hy': '🇦🇲 Հայերեն', 'az': '🇦🇿 Azərbaycanca', 'eu': '🇪🇸 Euskara',
    'be': '🇧🇾 Беларуская', 'bs': '🇧🇦 Bosanski', 'bg': '🇧🇬 Български',
    'ca': '🇪🇸 Català', 'hr': '🇭🇷 Hrvatski', 'et': '🇪🇪 Eesti',
    'gl': '🇪🇸 Galego', 'ka': '🇬🇪 ქართული', 'is': '🇮🇸 Íslenska',
    'ga': '🇮🇪 Gaeilge', 'jw': '🇮🇩 Basa Jawa', 'su': '🇮🇩 Basa Sunda',
    'my': '🇲🇲 မြန်မာ', 'km': '🇰🇭 ខ្មែរ', 'lo': '🇱🇦 ລາວ',
    'ne': '🇳🇵 नेपाली', 'si': '🇱🇰 සිංහල', 'mn': '🇲🇳 Монгол',
    'cy': '🏴 Cymraeg', 'mt': '🇲🇹 Malti', 'mk': '🇲🇰 Македонски',
    'lb': '🇱🇺 Lëtzebuergesch', 'nn': '🇳🇴 Nynorsk',
    'ha': '🇳🇬 Hausa', 'ig': '🇳🇬 Igbo', 'yo': '🇳🇬 Yorùbá',
    'zu': '🇿🇦 isiZulu', 'xh': '🇿🇦 isiXhosa', 'sn': '🇿🇼 chiShona',
    'mg': '🇲🇬 Malagasy', 'so': '🇸🇴 Soomaali', 'ti': '🇪🇹 ትግርኛ',
    'rw': '🇷🇼 Kinyarwanda', 'ny': '🇲🇼 Chichewa', 'st': '🇿🇦 Sesotho',
    'tg': '🇹🇯 Тоҷикӣ', 'tk': '🇹🇲 Türkmençe',
    'ky': '🇰🇬 Кыргызча', 'uz': '🇺🇿 Oʻzbekcha', 'kk': '🇰🇿 Қазақша',
    'bo': '🇨🇳 བོད་ཡིག', 'ug': '🇨🇳 ئۇيغۇرچە', 'ps': '🇦🇫 پښتو',
    'sd': '🇵🇰 سنڌي', 'ku': '🇹🇷 Kurdî', 'ckb': '🇮🇶 كوردی',
  };

  static final Map<String, Map<String, String>> _strings = {
    'id': {
      'app_name': 'DARKVERSE',
      'login': 'MASUK',
      'logout': 'KELUAR',
      'username': 'Username',
      'password': 'Password',
      'settings': 'Pengaturan',
      'language': 'Bahasa',
      'font': 'Font Teks',
      'font_size': 'Ukuran Teks',
      'font_weight': 'Tebal Teks',
      'chat': 'Chat',
      'public_chat': 'PUBLIC CHAT',
      'voice_channel': 'VOICE CHANNEL',
      'send': 'KIRIM',
      'type_message': 'Ketik pesan...',
      'reply': 'Balas',
      'camera': 'Kamera',
      'gallery': 'Galeri',
      'photo': 'Foto',
      'video': 'Video',
      'voice_note': 'Voice Note',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'join': 'GABUNG',
      'leave': 'KELUAR',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'speaker': 'Speaker',
      'end_call': 'Akhiri',
      'launch_attack': 'LAUNCH ATTACK',
      'attack_success': 'Berhasil!',
      'attack_failed': 'Gagal',
      'cooldown': 'Tunggu sebentar',
      'invalid_number': 'Nomor tidak valid',
      'invalid_link': 'Link tidak valid',
      'connection_error': 'Koneksi gagal',
      'biometric_login': 'Login dengan sidik jari',
      'biometric_enable': 'Aktifkan Biometric?',
      'biometric_desc': 'Aktifkan login dengan sidik jari/face ID agar tidak perlu memasukkan password lagi?',
      'biometric_yes': 'Aktifkan',
      'biometric_later': 'Nanti Saja',
      'device_security': 'KEAMANAN PERANGKAT',
      'trusted_devices': 'Perangkat Terpercaya',
      'verify_device': 'Verifikasi Perangkat',
      'verify_desc': 'Masukkan 6 digit kode verifikasi dari perangkat lama',
      'verify_code': 'Kode Verifikasi',
      'verify_btn': 'Verifikasi',
      'cancel': 'Batal',
      'close': 'Tutup',
      'change_password': 'Ubah Password',
      'expired': 'Kadaluarsa',
      'role': 'Role',
      'session_key': 'Session Key',
      'profile': 'Profil',
      'tools': 'Tools',
      'loading': 'Memuat...',
      'search': 'Cari',
      'save': 'Simpan',
      'delete': 'Hapus',
      'edit': 'Edit',
      'confirm': 'Konfirmasi',
      'yes': 'Ya',
      'no': 'Tidak',
      'ok': 'OK',
      'error': 'Error',
      'success': 'Berhasil',
      'warning': 'Peringatan',
      'info': 'Info',
      'no_messages': 'Belum ada pesan',
      'recording': 'Merekam...',
      'participants': 'peserta',
      'no_devices': 'Belum ada device terdaftar',
      'revoke': 'HAPUS',
      'current_device': 'Perangkat ini',
      'font_family': 'Jenis Font',
      'font_style': 'Gaya Teks',
      'text_color': 'Warna Teks',
      'preview': 'Preview',
      'apply': 'Terapkan',
      'reset': 'Reset',
      'activity_history': 'Riwayat Aktivitas',
      'my_profile': 'Profil Saya',
      'owner_panel': 'Panel Owner',
      'admin_panel': 'Panel Admin',
      'seller_panel': 'Panel Seller',
      'settings': 'Pengaturan',
    },
    'en': {
      'app_name': 'DARKVERSE',
      'login': 'LOGIN',
      'logout': 'LOGOUT',
      'username': 'Username',
      'password': 'Password',
      'settings': 'Settings',
      'language': 'Language',
      'font': 'Text Font',
      'font_size': 'Text Size',
      'font_weight': 'Text Weight',
      'chat': 'Chat',
      'public_chat': 'PUBLIC CHAT',
      'voice_channel': 'VOICE CHANNEL',
      'send': 'SEND',
      'type_message': 'Type a message...',
      'reply': 'Reply',
      'camera': 'Camera',
      'gallery': 'Gallery',
      'photo': 'Photo',
      'video': 'Video',
      'voice_note': 'Voice Note',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'join': 'JOIN',
      'leave': 'LEAVE',
      'mute': 'Mute',
      'unmute': 'Unmute',
      'speaker': 'Speaker',
      'end_call': 'End',
      'launch_attack': 'LAUNCH ATTACK',
      'attack_success': 'Success!',
      'attack_failed': 'Failed',
      'cooldown': 'Please wait',
      'invalid_number': 'Invalid number',
      'invalid_link': 'Invalid link',
      'connection_error': 'Connection error',
      'biometric_login': 'Login with fingerprint',
      'biometric_enable': 'Enable Biometric?',
      'biometric_desc': 'Enable fingerprint/face ID login so you don\'t need to enter password again?',
      'biometric_yes': 'Enable',
      'biometric_later': 'Later',
      'device_security': 'DEVICE SECURITY',
      'trusted_devices': 'Trusted Devices',
      'verify_device': 'Verify Device',
      'verify_desc': 'Enter the 6-digit verification code from your old device',
      'verify_code': 'Verification Code',
      'verify_btn': 'Verify',
      'cancel': 'Cancel',
      'close': 'Close',
      'change_password': 'Change Password',
      'expired': 'Expired',
      'role': 'Role',
      'session_key': 'Session Key',
      'profile': 'Profile',
      'tools': 'Tools',
      'loading': 'Loading...',
      'search': 'Search',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'confirm': 'Confirm',
      'yes': 'Yes',
      'no': 'No',
      'ok': 'OK',
      'error': 'Error',
      'success': 'Success',
      'warning': 'Warning',
      'info': 'Info',
      'no_messages': 'No messages yet',
      'recording': 'Recording...',
      'participants': 'participants',
      'no_devices': 'No trusted devices yet',
      'revoke': 'REMOVE',
      'current_device': 'This device',
      'font_family': 'Font Family',
      'font_style': 'Text Style',
      'text_color': 'Text Color',
      'preview': 'Preview',
      'apply': 'Apply',
      'reset': 'Reset',
      'activity_history': 'Activity History',
      'my_profile': 'My Profile',
      'owner_panel': 'Owner Panel',
      'admin_panel': 'Admin Panel',
      'seller_panel': 'Seller Panel',
    },
    'ja': {
      'app_name': 'DARKVERSE',
      'login': 'ログイン',
      'logout': 'ログアウト',
      'username': 'ユーザー名',
      'password': 'パスワード',
      'settings': '設定',
      'language': '言語',
      'font': 'フォント',
      'font_size': 'テキストサイズ',
      'font_weight': 'テキストの太さ',
      'chat': 'チャット',
      'public_chat': ' PUBLIC CHAT',
      'voice_channel': 'ボイスチャンネル',
      'send': '送信',
      'type_message': 'メッセージを入力...',
      'reply': '返信',
      'camera': 'カメラ',
      'gallery': 'ギャラリー',
      'photo': '写真',
      'video': '動画',
      'voice_note': 'ボイスメッセージ',
      'online': 'オンライン',
      'offline': 'オフライン',
      'join': '参加',
      'leave': '退出',
      'mute': 'ミュート',
      'unmute': 'ミュート解除',
      'speaker': 'スピーカー',
      'end_call': '終了',
      'launch_attack': 'アタック開始',
      'attack_success': '成功！',
      'attack_failed': '失敗',
      'cooldown': 'しばらくお待ちください',
      'invalid_number': '無効な番号',
      'invalid_link': '無効なリンク',
      'connection_error': '接続エラー',
      'no_messages': 'メッセージなし',
      'recording': '録音中...',
      'participants': '参加者',
      'cancel': 'キャンセル',
      'close': '閉じる',
      'save': '保存',
      'delete': '削除',
      'edit': '編集',
      'confirm': '確認',
      'yes': 'はい',
      'no': 'いいえ',
      'ok': 'OK',
      'error': 'エラー',
      'success': '成功',
      'loading': '読み込み中...',
      'preview': 'プレビュー',
      'apply': '適用',
      'reset': 'リセット',
    },
    'ko': {
      'app_name': 'DARKVERSE',
      'login': '로그인',
      'logout': '로그아웃',
      'username': '사용자 이름',
      'password': '비밀번호',
      'settings': '설정',
      'language': '언어',
      'font': '글꼴',
      'chat': '채팅',
      'public_chat': '퍼블릭 채팅',
      'voice_channel': '보이스 채널',
      'send': '보내기',
      'type_message': '메시지 입력...',
      'reply': '답장',
      'online': '온라인',
      'offline': '오프라인',
      'join': '참가',
      'leave': '나가기',
      'mute': '음소거',
      'cancel': '취소',
      'close': '닫기',
      'save': '저장',
      'delete': '삭제',
      'loading': '로딩...',
      'preview': '미리보기',
      'apply': '적용',
      'reset': '초기화',
    },
    'zh': {
      'app_name': 'DARKVERSE',
      'login': '登录',
      'logout': '退出',
      'username': '用户名',
      'password': '密码',
      'settings': '设置',
      'language': '语言',
      'font': '字体',
      'chat': '聊天',
      'public_chat': '公共聊天',
      'voice_channel': '语音频道',
      'send': '发送',
      'type_message': '输入消息...',
      'reply': '回复',
      'online': '在线',
      'offline': '离线',
      'join': '加入',
      'leave': '离开',
      'mute': '静音',
      'cancel': '取消',
      'close': '关闭',
      'save': '保存',
      'delete': '删除',
      'loading': '加载中...',
      'preview': '预览',
      'apply': '应用',
      'reset': '重置',
    },
    'ar': {
      'app_name': 'DARKVERSE',
      'login': 'تسجيل الدخول',
      'logout': 'تسجيل الخروج',
      'username': 'اسم المستخدم',
      'password': 'كلمة المرور',
      'settings': 'الإعدادات',
      'language': 'اللغة',
      'font': 'الخط',
      'chat': 'المحادثة',
      'public_chat': 'المحادثة العامة',
      'voice_channel': 'قناة الصوت',
      'send': 'إرسال',
      'type_message': 'اكتب رسالة...',
      'reply': 'رد',
      'online': 'متصل',
      'offline': 'غير متصل',
      'join': 'انضم',
      'leave': 'مغادرة',
      'mute': 'كتم',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'save': 'حفظ',
      'delete': 'حذف',
      'loading': 'جاري التحميل...',
      'preview': 'معاينة',
      'apply': 'تطبيق',
      'reset': 'إعادة تعيين',
    },
    'fr': {
      'app_name': 'DARKVERSE',
      'login': 'CONNEXION',
      'logout': 'DÉCONNEXION',
      'username': 'Nom d\'utilisateur',
      'password': 'Mot de passe',
      'settings': 'Paramètres',
      'language': 'Langue',
      'font': 'Police',
      'chat': 'Chat',
      'public_chat': 'CHAT PUBLIC',
      'voice_channel': 'CANAL VOCAL',
      'send': 'ENVOYER',
      'type_message': 'Tapez un message...',
      'reply': 'Répondre',
      'online': 'EN LIGNE',
      'offline': 'HORS LIGNE',
      'join': 'REJOINDRE',
      'leave': 'QUITTER',
      'mute': 'Muet',
      'cancel': 'Annuler',
      'close': 'Fermer',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'loading': 'Chargement...',
      'preview': 'Aperçu',
      'apply': 'Appliquer',
      'reset': 'Réinitialiser',
    },
    'de': {
      'app_name': 'DARKVERSE',
      'login': 'ANMELDEN',
      'logout': 'ABMELDEN',
      'username': 'Benutzername',
      'password': 'Passwort',
      'settings': 'Einstellungen',
      'language': 'Sprache',
      'font': 'Schriftart',
      'chat': 'Chat',
      'public_chat': 'ÖFFENTLICHER CHAT',
      'voice_channel': 'SPRECHKANAL',
      'send': 'SENDEN',
      'type_message': 'Nachricht eingeben...',
      'reply': 'Antworten',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'join': 'BEITRETEN',
      'leave': 'VERLASSEN',
      'mute': 'Stumm',
      'cancel': 'Abbrechen',
      'close': 'Schließen',
      'save': 'Speichern',
      'delete': 'Löschen',
      'loading': 'Laden...',
      'preview': 'Vorschau',
      'apply': 'Anwenden',
      'reset': 'Zurücksetzen',
    },
    'es': {
      'app_name': 'DARKVERSE',
      'login': 'INICIAR SESIÓN',
      'logout': 'CERRAR SESIÓN',
      'username': 'Usuario',
      'password': 'Contraseña',
      'settings': 'Ajustes',
      'language': 'Idioma',
      'font': 'Fuente',
      'chat': 'Chat',
      'public_chat': 'CHAT PÚBLICO',
      'voice_channel': 'CANAL DE VOZ',
      'send': 'ENVIAR',
      'type_message': 'Escribe un mensaje...',
      'reply': 'Responder',
      'online': 'EN LÍNEA',
      'offline': 'DESCONECTADO',
      'join': 'UNIRSE',
      'leave': 'SALIR',
      'mute': 'Silenciar',
      'cancel': 'Cancelar',
      'close': 'Cerrar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'loading': 'Cargando...',
      'preview': 'Vista previa',
      'apply': 'Aplicar',
      'reset': 'Restablecer',
    },
    'pt': {
      'app_name': 'DARKVERSE',
      'login': 'ENTRAR',
      'logout': 'SAIR',
      'username': 'Usuário',
      'password': 'Senha',
      'settings': 'Configurações',
      'language': 'Idioma',
      'font': 'Fonte',
      'chat': 'Chat',
      'public_chat': 'CHAT PÚBLICO',
      'voice_channel': 'CANAL DE VOZ',
      'send': 'ENVIAR',
      'type_message': 'Digite uma mensagem...',
      'reply': 'Responder',
      'online': 'ONLINE',
      'offline': 'OFFLINE',
      'join': 'ENTRAR',
      'leave': 'SAIR',
      'mute': 'Silenciar',
      'cancel': 'Cancelar',
      'close': 'Fechar',
      'save': 'Salvar',
      'delete': 'Excluir',
      'loading': 'Carregando...',
      'preview': 'Visualizar',
      'apply': 'Aplicar',
      'reset': 'Redefinir',
    },
    'ru': {
      'app_name': 'DARKVERSE',
      'login': 'ВОЙТИ',
      'logout': 'ВЫЙТИ',
      'username': 'Имя пользователя',
      'password': 'Пароль',
      'settings': 'Настройки',
      'language': 'Язык',
      'font': 'Шрифт',
      'chat': 'Чат',
      'public_chat': 'ПУБЛИЧНЫЙ ЧАТ',
      'voice_channel': 'ГОЛОСОВОЙ КАНАЛ',
      'send': 'ОТПРАВИТЬ',
      'type_message': 'Введите сообщение...',
      'reply': 'Ответить',
      'online': 'ОНЛАЙН',
      'offline': 'ОФФЛАЙН',
      'join': 'ПРИСОЕДИНИТЬСЯ',
      'leave': 'ВЫЙТИ',
      'mute': 'Отключить звук',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'save': 'Сохранить',
      'delete': 'Удалить',
      'loading': 'Загрузка...',
      'preview': 'Предпросмотр',
      'apply': 'Применить',
      'reset': 'Сбросить',
    },
    'hi': {
      'app_name': 'DARKVERSE',
      'login': 'लॉग इन',
      'logout': 'लॉग आउट',
      'username': 'उपयोगकर्ता नाम',
      'password': 'पासवर्ड',
      'settings': 'सेटिंग्स',
      'language': 'भाषा',
      'font': 'फ़ॉन्ट',
      'chat': 'चैट',
      'public_chat': 'पब्लिक चैट',
      'voice_channel': 'वॉयस चैनल',
      'send': 'भेजें',
      'type_message': 'संदेश टाइप करें...',
      'reply': 'जवाब दें',
      'online': 'ऑनलाइन',
      'offline': 'ऑफलाइन',
      'join': 'शामिल हों',
      'leave': '�ोड़ें',
      'mute': 'म्यूट',
      'cancel': 'रद्द करें',
      'close': 'बंद करें',
      'save': 'सहेजें',
      'delete': 'हटाएं',
      'loading': 'लोड हो रहा है...',
      'preview': 'पूर्वावलोकन',
      'apply': 'लागू करें',
      'reset': 'रीसेट',
    },
    'tr': {
      'app_name': 'DARKVERSE',
      'login': 'GİRİŞ',
      'logout': 'ÇIKIŞ',
      'username': 'Kullanıcı adı',
      'password': 'Şifre',
      'settings': 'Ayarlar',
      'language': 'Dil',
      'font': 'Yazı Tipi',
      'chat': 'Sohbet',
      'public_chat': 'HERKESE AÇIK SOHBET',
      'voice_channel': 'SES KANALI',
      'send': 'GÖNDER',
      'type_message': 'Mesaj yazın...',
      'reply': 'Yanıtla',
      'online': 'ÇEVRİMİÇİ',
      'offline': 'ÇEVRIMDIŞI',
      'join': 'KATIL',
      'leave': 'AYRIL',
      'mute': 'Sessiz',
      'cancel': 'İptal',
      'close': 'Kapat',
      'save': 'Kaydet',
      'delete': 'Sil',
      'loading': 'Yükleniyor...',
      'preview': 'Önizleme',
      'apply': 'Uygula',
      'reset': 'Sıfırla',
    },
    'vi': {
      'app_name': 'DARKVERSE',
      'login': 'ĐĂNG NHẬP',
      'logout': 'ĐĂNG XUẤT',
      'username': 'Tên người dùng',
      'password': 'Mật khẩu',
      'settings': 'Cài đặt',
      'language': 'Ngôn ngữ',
      'font': 'Phông chữ',
      'chat': 'Trò chuyện',
      'public_chat': 'TRÒ CHUYỆN CÔNG KHAI',
      'voice_channel': 'KÊNH GIỌNG NÓI',
      'send': 'GỬI',
      'type_message': 'Nhập tin nhắn...',
      'reply': 'Trả lời',
      'online': 'TRỰC TUYẾN',
      'offline': 'ngoại tuyến',
      'join': 'THAM GIA',
      'leave': 'RỜI ĐI',
      'mute': 'Tắt tiếng',
      'cancel': 'Hủy',
      'close': 'Đóng',
      'save': 'Lưu',
      'delete': 'Xóa',
      'loading': 'Đang tải...',
      'preview': 'Xem trước',
      'apply': 'Áp dụng',
      'reset': 'Đặt lại',
    },
    'ms': {
      'app_name': 'DARKVERSE',
      'login': 'LOG MASUK',
      'logout': 'LOG KELUAR',
      'username': 'Nama Pengguna',
      'password': 'Kata Laluan',
      'settings': 'Tetapan',
      'language': 'Bahasa',
      'font': 'Fon',
      'chat': 'Sembang',
      'public_chat': 'SEMBAANG AWAM',
      'voice_channel': 'SALURAN SUARA',
      'send': 'HANTAR',
      'type_message': 'Taip mesej...',
      'reply': 'Balas',
      'online': 'DALAM TALIAN',
      'offline': 'LUAR TALIAN',
      'join': 'SERTAI',
      'leave': 'KELUAR',
      'mute': 'Senyap',
      'cancel': 'Batal',
      'close': 'Tutup',
      'save': 'Simpan',
      'delete': 'Padam',
      'loading': 'Memuatkan...',
      'preview': 'Pratonton',
      'apply': 'Guna',
      'reset': 'Tetap Semula',
    },
    'tl': {
      'app_name': 'DARKVERSE',
      'login': 'MAG-LOGIN',
      'logout': 'MAG-LOGOUT',
      'username': 'Username',
      'password': 'Password',
      'settings': 'Settings',
      'language': 'Wika',
      'font': 'Font',
      'chat': 'Chat',
      'public_chat': 'PUBLIKO CHAT',
      'voice_channel': 'BOSES NA CHANNEL',
      'send': 'MAG-SEND',
      'type_message': 'Mag-type ng mensahe...',
      'reply': 'Sumagot',
      'online': 'NAG-OONLINE',
      'offline': 'NAG-OFFLINE',
      'join': 'SALI',
      'leave': 'UMALIS',
      'mute': 'I-mute',
      'cancel': 'Kanselahin',
      'close': 'Isara',
      'save': 'I-save',
      'delete': 'Tanggalin',
      'loading': 'Naglo-load...',
      'preview': 'Preview',
      'apply': 'I-apply',
      'reset': 'I-reset',
    },
  };

  // Default fallback
  static const Map<String, String> _fallback = {};

  static Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _current = prefs.getString('app_language') ?? 'id';
  }

  static Future<void> setLanguage(String code) async {
    _current = code;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('app_language', code);
  }

  static String t(String key) {
    final lang = _strings[_current];
    if (lang != null && lang.containsKey(key)) return lang[key]!;
    // Fallback to Indonesian
    final idLang = _strings['id'];
    if (idLang != null && idLang.containsKey(key)) return idLang[key]!;
    return key;
  }

  static List<MapEntry<String, String>> get supportedLanguages {
    return _meta.entries.toList()..sort((a, b) => a.value.compareTo(b.value));
  }

  static String languageName(String code) => _meta[code] ?? code;
}
